channels_chatroom/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^', include('chatroom.urls', namespace='chatroom')),
]

chatroom/urls.py
from django.conf.urls import url
from chatroom import views

app_name = 'chatroom'

urlpatterns = [
    url(r'^$',  views.about, name='about'),
    url(r'^new/$', views.new_room, name='new_room'),
    url(r'^(?P<label>[\w-]{,50})/$', views.chat_room, name='chat_room'),
]

chatroom/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Room(models.Model):
    name  = models.TextField()
    label = models.SlugField(unique=True)

class Message(models.Model):
    room      = models.ForeignKey(Room, related_name='messages', on_delete=models.CASCADE)
    handle    = models.TextField()
    message   = models.TextField()
    timestamp = models.DateTimeField(default=timezone.now, db_index=True)

chatroom/views.py
import haikunator
from django.db import transaction
from django.urls import reverse
from django.shortcuts import render, redirect
from chatroom.models import Room

# Create your views here.
def about(request):
    return render(request, 'chatroom/about.html')

def new_room(request):
    """
    Randomly create a new room, and redirect to it.
    """
    new_room = None
    while not new_room:
        with transaction.atomic():
            label = haikunator.Haikunator().haikunate()
            if Room.objects.filter(label=label).exists():
                continue
            new_room = Room.objects.create(label=label)
    return redirect(reverse('chatroom:chat_room', args=(label,)))

def chat_room(request, label):
    room, created = Room.objects.get_or_create(label=label)

    messages = reversed(room.messages.order_by('-timestamp')[:50])

    return render(request, 'chatroom/room.html', {'room': room, 'messages': messages})

templates/chatroom/about.html
{% extends "chatroom/base.html" %}

{% block content %}
  <h1>Django Channels Example</h1>
  <p class="deck">
    This is a demo using <a href="http://channels.readthedocs.org/en/latest/">
    Django Channels</a> to implement a simple WebSocket-based chat server.
    You can see the <a href="https://github.com/jacobian/channels-example">
    code on GitHub</a>, or try the app:
  </p>
  <p>
    <a class="button button-primary" href="{% url 'chatroom:new_room' %}">Create new chat room</a>
  </p>
  <p class="quiet">
    Or, you can visit <code>{{ request.scheme }}://{{ request.get_host }}/any-path-you-want</code> 
    to create a arbitrary room or join one whose name you know.
  </p>
{% endblock content %}

templates/chatroom/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>{% block title %}Django Channels Example{% endblock %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href='{% static "google-fonts.css" %}' rel='stylesheet' type='text/css'>
  {% load staticfiles %}
  <link rel="stylesheet" href="{% static 'normalize.css' %}">
  <link rel="stylesheet" href="{% static 'skeleton.css' %}">
  <link rel="stylesheet" href="{% static 'chat.css' %}">
</head>
<body>
  <div class="section">
    <div class="container">
      {% block content %}{% endblock content %}
    </div>
  </div>  
  {% block afterbody %}{% endblock afterbody %}
  <a href="https://github.com/jacobian/channels-example">
    <img style="position: absolute; top: 0; right: 0; border: 0;"
         src="https://camo.githubusercontent.com/a6677b08c955af8400f44c6298f40e7d19cc5b2d/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f6769746875622f726962626f6e732f666f726b6d655f72696768745f677261795f3664366436642e706e67"
         alt="Fork me on GitHub"
         data-canonical-src="https://s3.amazonaws.com/github/ribbons/forkme_right_gray_6d6d6d.png" />
  </a>
</body>
</html>

templates/chatroom/room.html
{% extends "chatroom/base.html" %}

{% block content %}
  {% load staticfiles %}
  <h1>{{ room.label }}</h1>
  <p class="quiet">
    Anyone with this URL can join the room and chat: 
    <code>{{ request.scheme }}://{{ request.get_host }}/{{ room.label }}</code> 
  </p>
  <p>
    <label for="handle">Your name:</label>
    <input id="handle" type="text" placeholder="handle">
  </p>
  <form id="chatform">
    <table id="chat">
      <tbody>
        {% for message in messages %}
          <tr>
            <td>{{ message.formatted_timestamp }}</td>
            <td>{{ message.handle }}</td>
            <td>{{ message.message }}</td>
          </tr> 
        {% endfor %}
      </tbody>
      <tfoot>
      <tr>
        <td>Say something:</td>
        <td colspan=2>
          <input id="message" type="text" placeholder="message">
          <button type="submit" id="go">Say it</button>
        </td>
      </tfoot>
    </table>
  </form>
{% endblock content %}

{% block afterbody %}
  <script type="text/javascript" src='{% static "jquery-1.12.1.min.js" %}'></script>
  <script type="text/javascript" src='{% static "reconnecting-websocket.min.js" %}'></script>
  <script type="text/javascript" src='{% static "chat.js" %}'></script>
{% endblock afterbody %}